from .base_model import BaseModel
from .departments import Departments
from .employees import Employees
from .employees_in_departments import EmployeesInDepartments
from .prefessions import Professions
from .employees_professions import EmployeesProfessions
from .incidents import Incidents
from .safety_briefings import SafetyBriefings
from .briefed_employees import BriefedEmployees
from .users import Users
from .admins import Admins